"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import { AnimatePresence } from "framer-motion";
import { useState } from "react";
import MountContext from "@/components/Context";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isFirstMount, setIsFirstMount] = useState(true);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation>
          <AnimatePresence mode="wait">
            <MountContext.Provider value={{ isFirstMount, setIsFirstMount }}>
              {children}
            </MountContext.Provider>
          </AnimatePresence>
        </Navigation>
      </body>
    </html>
  );
}
